apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: sureshrevathi/customer:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URL
          value: "mongodb://mongodb-service:27017"
